[FileDialog]
history=file:///home/randy/hdddata/books, file:///home/randy/hdddata/downloads_hdd/endict/dict, file:///home/randy/hdddata/downloads_hdd, file:///home/randy/hdddata/downloads_hdd/english_we_like_study/coca-vocabulary-20000/vocabulary, file:///home/randy/.local/share/Anki2/addons21/1210908941/user_files/background, file:///home/randy/hdddata
lastVisited=file:///home/randy/hdddata
qtVersion=6.11.1
shortcuts=file:, file:///home/randy
sidebarWidth=114
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2l\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1G\0\0\0\x1\0\0\0\0\0\0\0L\0\0\0\x1\0\0\0\0\0\0\0Q\0\0\0\x1\0\0\0\0\0\0\0\x88\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
