github.com:
    users:
        rabbit0620:
            oauth_token: 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
    git_protocol: https
    user: rabbit0620
    oauth_token: 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
